---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jawacode/public_html
    - /bin/rsync -a --exclude='.git' --exclude='vendor' . $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/php -d memory_limit=-1 /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
    # - cp .env.example .env
    - /usr/local/bin/php artisan key:generate
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan migrate --force
