---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jawacode/public_html
    - cd $DEPLOYPATH
    - git pull origin main
    - /opt/cpanel/composer/bin/composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
